version: '3'
services:
  slackboit:
    container_name: bigweeb
    image: davonbarnette/bigweeb
    volumes:
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    env_file:
      - ./env/prod.env
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    env_file:
      - ./env/watchtower.prod.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup

