TOKEN="NzQ0MDE2NjI1Nzg2NjgzNTE0.XzdFeg.tEmmUkgFRl_IRu6HI2Lq6l_oXqQ"
YOUTUBE_API_KEY="AIzaSyDBtramu8na-WobF7lJDETZ2iQPrdHPCeA"
SOUNDCLOUD_CLIENT_ID=""
MAX_PLAYLIST_SIZE=10
PREFIX="$"
PRUNING=false
SAVE_CLIENT_ID=false
GOOGLE_APPLICATION_CREDENTIALS="./translate-service-account.json"